%% 全国房价
filename = './dataSets/2003-2022国内主要城市住宅商品房平均销售价格.csv';
inData = readmatrix(filename,'Range','B5:U40');
labelnames = readcell(filename,'Range','A5:A40');
timesStr = string(2003:2022);
inData = fillmissing(inData,'constant',0.1);

% 整理成合适的格式
inData = fliplr(inData);
labels = categorical(labelnames);
h = barChartRace2(inData,...
    "TopK",10,...
    "Categories",labels,...
    "TimeLabels",timesStr,...
    "FramesPerDataTick",100,...
    "TitleLabel",'2003-2022国内主要城市住宅商品房平均销售价格（元/平米）',...
    "GenerateGIF",false);
